---
title: "CodeBook"
author: "Duc Doan"
date: "December 31, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepapre the data set
```{r, cache=FALSE, eval=TRUE}
# directory for reading the data files
trainingDataDir <- "./UCI\ HAR\ Dataset/train/"
testingDataDir <- "./UCI\ HAR\ Dataset/test/"
dataDir <- "./UCI\ HAR\ Dataset/"
trainingInertDataDir <- "./UCI\ HAR\ Dataset/train/Inertial\ Signals/"
testingInertDataDir <- "./UCI\ HAR\ Dataset/test/Inertial\ Signals/"

# read data files
# activity labels and features
act_labs <- read.csv(paste(dataDir, "activity_labels.txt", sep = ""), header = FALSE, sep = "")
fea_name <- read.csv(paste(dataDir, "features.txt", sep = ""), header = FALSE, sep = "") 

#################################### read training data ######################################
X_train <- read.csv(paste(trainingDataDir, "X_train.txt", sep = ""), header = FALSE, sep = "")
y_train <- read.csv(paste(trainingDataDir, "y_train.txt", sep = ""), header = FALSE, sep = "")

dim(X_train)
dim(y_train)

# subject
subj_train <- read.csv(paste(trainingDataDir, "subject_train.txt", sep = ""), header = FALSE, sep = "")

dim(subj_train)

# other data
# body acceleration x, y, z
body_acc_x_train <- read.csv(paste(trainingInertDataDir, "body_acc_x_train.txt", sep = ""), header = FALSE, sep = "")
body_acc_y_train <- read.csv(paste(trainingInertDataDir, "body_acc_y_train.txt", sep = ""), header = FALSE, sep = "")
body_acc_z_train <- read.csv(paste(trainingInertDataDir, "body_acc_z_train.txt", sep = ""), header = FALSE, sep = "")

dim(body_acc_x_train)
dim(body_acc_y_train)
dim(body_acc_z_train)

# body gyro x, y, z
body_gyro_x_train <- read.csv(paste(trainingInertDataDir, "body_gyro_x_train.txt", sep = ""), header = FALSE, sep = "")
body_gyro_y_train <- read.csv(paste(trainingInertDataDir, "body_gyro_y_train.txt", sep = ""), header = FALSE, sep = "")
body_gyro_z_train <- read.csv(paste(trainingInertDataDir, "body_gyro_z_train.txt", sep = ""), header = FALSE, sep = "")

dim(body_gyro_x_train)
dim(body_gyro_y_train)
dim(body_gyro_z_train)

# total acceleration x, y, z
total_acc_x_train <- read.csv(paste(trainingInertDataDir, "total_acc_x_train.txt", sep = ""), header = FALSE, sep = "")
total_acc_y_train <- read.csv(paste(trainingInertDataDir, "total_acc_y_train.txt", sep = ""), header = FALSE, sep = "")
total_acc_z_train <- read.csv(paste(trainingInertDataDir, "total_acc_z_train.txt", sep = ""), header = FALSE, sep = "")

dim(total_acc_x_train)
dim(total_acc_y_train)
dim(total_acc_z_train)
#############################################################################################

#################################### read testing data ######################################
X_test <- read.csv(paste(testingDataDir, "X_test.txt", sep = ""), header = FALSE, sep = "")
y_test <- read.csv(paste(testingDataDir, "y_test.txt", sep = ""), header = FALSE, sep = "")

dim(X_test)
dim(y_test)

# subject
subj_test <- read.csv(paste(testingDataDir, "subject_test.txt", sep = ""), header = FALSE, sep = "")

dim(subj_test)

# other data
# body acceleration x, y, z
body_acc_x_test <- read.csv(paste(testingInertDataDir, "body_acc_x_test.txt", sep = ""), header = FALSE, sep = "")
body_acc_y_test <- read.csv(paste(testingInertDataDir, "body_acc_y_test.txt", sep = ""), header = FALSE, sep = "")
body_acc_z_test <- read.csv(paste(testingInertDataDir, "body_acc_z_test.txt", sep = ""), header = FALSE, sep = "")

dim(body_acc_x_test)
dim(body_acc_y_test)
dim(body_acc_z_test)

# body gyro x, y, z
body_gyro_x_test <- read.csv(paste(testingInertDataDir, "body_gyro_x_test.txt", sep = ""), header = FALSE, sep = "")
body_gyro_y_test <- read.csv(paste(testingInertDataDir, "body_gyro_y_test.txt", sep = ""), header = FALSE, sep = "")
body_gyro_z_test <- read.csv(paste(testingInertDataDir, "body_gyro_z_test.txt", sep = ""), header = FALSE, sep = "")

dim(body_gyro_x_test)
dim(body_gyro_y_test)
dim(body_gyro_z_test)

# total acceleration x, y, z
total_acc_x_test <- read.csv(paste(testingInertDataDir, "total_acc_x_test.txt", sep = ""), header = FALSE, sep = "")
total_acc_y_test <- read.csv(paste(testingInertDataDir, "total_acc_y_test.txt", sep = ""), header = FALSE, sep = "")
total_acc_z_test <- read.csv(paste(testingInertDataDir, "total_acc_z_test.txt", sep = ""), header = FALSE, sep = "")

dim(total_acc_x_test)
dim(total_acc_y_test)
dim(total_acc_z_test)
############################################################################################
```

## (1) Merge the training and test data sets to create one data set
```{r, cache=FALSE, eval=TRUE}
####################################################################
# the data set for training and testing
Xy_train <- cbind(X_train, c(subj_train, y_train))
Xy_test <- cbind(X_test, c(subj_test, y_test))
Xy_dataset <- rbind(Xy_train, Xy_test)
dim(Xy_dataset)

# body acc. x, y, z
body_acc_x_data <- rbind(body_acc_x_train, body_acc_x_test)
body_acc_y_data <- rbind(body_acc_y_train, body_acc_y_test)
body_acc_z_data <- rbind(body_acc_z_train, body_acc_z_test)

dim(body_acc_x_data)
dim(body_acc_y_data)
dim(body_acc_z_data)

# body gyro. x, y, z
body_gyro_x_data <- rbind(body_gyro_x_train, body_gyro_x_test)
body_gyro_y_data <- rbind(body_gyro_y_train, body_gyro_y_test)
body_gyro_z_data <- rbind(body_gyro_z_train, body_gyro_z_test)

dim(body_gyro_x_data)
dim(body_gyro_y_data)
dim(body_gyro_z_data)

# total acc. x, y, z
total_acc_x_data <- rbind(total_acc_x_train, total_acc_x_test)
total_acc_y_data <- rbind(total_acc_y_train, total_acc_y_test)
total_acc_z_data <- rbind(total_acc_z_train, total_acc_z_test)

dim(total_acc_x_data)
dim(total_acc_y_data)
dim(total_acc_z_data)
####################################################################
```

## (2) (3) (4) Name columns for the data set and extracts only the measurements on the mean and standard deviation for each measurement
```{r, cache=FALSE, eval=TRUE}
####################################################################
# names for data set 
colnames(Xy_dataset) <-  c(as.character.factor(fea_name[, 2]), "subject", "activity")
colnames(Xy_dataset)

# transform the column data in 'subject' and 'activity' to factor
Xy_dataset[, c("subject")] <- factor(Xy_dataset[, c("subject")])
Xy_dataset[, c("activity")] <- factor(Xy_dataset[, c("activity")])

# extracts the measurements on the mean and deviation
mean_std_data <- Xy_dataset[, grepl("mean", tolower(colnames(Xy_dataset))) | 
                                grepl("std", tolower(colnames(Xy_dataset))) == TRUE]
colnames(mean_std_data)
####################################################################
```

## (5) Create a second, independent tidy data set with the average of each variable for each activity and each subject
```{r, cache=FALSE, eval=TRUE}
####################################################################
avg_group_data <- list()
# group by activity
avg_group_data[[1]] <- sapply(split(subset(Xy_dataset, select = -c(subject, activity)), 
                                          Xy_dataset[, "activity"]), colMeans)

# group by subject
avg_group_data[[2]] <- sapply(split(subset(Xy_dataset, select = -c(subject, activity)), 
                                          Xy_dataset[, "subject"]), colMeans)
head(avg_group_data[[1]])
head(avg_group_data[[2]])
####################################################################
```